### ISSUE TITLE
I want to use java to calculate the offline transaction id

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eosio-java#101]
I want to use java to calculate the offline transaction id, but the actual calculation is inconsistent with the return of the chain, can you help me see it?

https://github.com/bcskill/eos-client/blob/9cfc6ebb00bd857f3dec68de7c79d69ab6b1f742/src/main/java/pe/freeopen/eosclient/EosClient.java#L60

**Comment by cppfuns** [comment]
@GonnaGitYou

**Comment by opi-smccoole** [comment]
`Hex.toHexString(Sha256Hash.hash(Hex.decode(processor.getSerializedTransaction())));` should do it.
