### ISSUE TITLE
Support nodeos 1.8 send_transaction

### ISSUE THREAD

**Issue by brandonfancher** [EOSIO/eosio-java#45]
nodeos 1.8 adds `/v1/send_transaction` to replace the legacy `/v1/push_transaction`.

`push_transaction` reproduces the legacy trace format; this increases the load on nodeos.

`send_transaction` produces the new trace format.
 
See Issue 539 in the eosjs repo.

**Comment by opi-smccoole** [comment]
Added in the 1.0 releases of the libraries.
