### ISSUE TITLE
How to calculate transaction_id in my programe with eosio-java

### ISSUE THREAD

**Issue by khiker007** [EOSIO/eosio-java#96]
I want calculate transaction_id in my programe,And I guess that must get the serializeTransaction,and then SHA256 it and toHEX will get the transaction_id (is correct?)

The class TransactionProcessor method serializeTransaction() dependency ISerializationProvider,but  I cant found the implementations int the code, dad not finish？

**Comment by khiker007** [comment]
@GonnaGitYou

**Comment by opi-smccoole** [comment]
`Hex.toHexString(Sha256Hash.hash(Hex.decode(processor.getSerializedTransaction())));` should do it.
